* 딥러닝을 구현하다 보면 배열이나 행렬 계산이 많이 등장한다. 이때 numpy를 사용하면 굉장히 편해진다

In [5]:
# numpy 불러오기
import numpy as np

In [4]:
# 넘파이 배열 생성
x = np.array([1.0, 2.0, 3.0])
print(type(x), (x))

<class 'numpy.ndarray'> [1. 2. 3.]


In [7]:
# 넘파이의 산술 연산
# 넘파이를 이용하여 산순연산을 할 때는 x와y의 원소수가 같다면 각 원소에 대해 행해진다.
# 이와같은 원소별 연산을 element-wise라 하며, 원소별 곱셈의 경우 element-wise product라고 한다.
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])
print(x + y)
print(x - y)
print(x * y)
print(x / y)

[3. 6. 9.]
[-1. -2. -3.]
[ 2.  8. 18.]
[0.5 0.5 0.5]


In [8]:
# 넘파이 배열과 수치하나(스칼라값)의 조합으로 된 산술 연산을 broadcast라고 한다.
# 스칼라값 하나가 배열 각각에 대해 한번씩 수행된다.
x = np.array([1.0, 2.0, 3.0])
print(x / 2.0)

[0.5 1.  1.5]


In [12]:
# 넘파이의 n차원 배열
a = np.array([[1, 2], [3, 4]])
print(a)
print(a.shape) 
print(a.dtype) # dtype을 통해서 행렬에 담긴 원소의 자료형을 알수가 있다.

[[1 2]
 [3 4]]
(2, 2)
int64


In [13]:
print(a)
print(a * 10) # 마찬가지로 브로드캐스트기능이 적용된다.

[[1 2]
 [3 4]]
[[10 20]
 [30 40]]


In [14]:
# 배열이 달라도 다음과 같이 브로드캐스트가 가능하다.
a = np.array([[1, 2], [3, 4]])
b = np.array([10, 20])
print(a * b)

[[10 40]
 [30 80]]


In [16]:
# 원소접근
x = np.array([[1, 2], [3, 4], [5, 6]])
print(x)
print(x[0])
print(x[0][0])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
1


In [18]:
x = x.flatten() # x를 1차원 배열로 변환(평탄화 작업)
print(x)

[1 2 3 4 5 6]


In [19]:
x[np.array([0, 2, 4])] # 다음과 같이 해당 인덱스가 0, 2, 4에 해당되는 원소들을 쉽게 얻을수 있다.

array([1, 3, 5])